version: "3.3"

services:
  snipphub-api:
    image: snipphub-api:dev
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0 ./bin/www
    depends_on:
      - snipphub-db
  snipphub-db:
    image: mongo:3.4
    volumes:
      - snipphub-data-dev:/data/db
    ports:
      - 27017:27017
volumes:
  snipphub-data-dev: