version: "3.3"

services:
  snipphub-api:
    image: snipphub-api:dev
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: ["./wait-for-it.sh", "snipphub-db:5432", "--", "./start-dev.sh"]
    depends_on:
      - snipphub-db
  snipphub-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: snipphub
      POSTGRES_PASSWORD: snipphub
    volumes:
      - snipphub-data-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
  snipphub-db-admin-gui:
    image: fenglc/pgadmin4
    environment:
      DEFAULT_USER: snipphub
      DEFAULT_PASSWORD: snipphub
    ports:
      - 5050:5050
    depends_on:
      - snipphub-db
volumes:
  snipphub-data-dev: