version: "3.3"

services:
  snipphub-api:
    image: snipphub-api:prod
    build: .
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "snipphub-db:5432", "--", "./start-prod.sh"]
    depends_on:
      - snipphub-db
  snipphub-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: snipphub
      POSTGRES_PASSWORD: snipphub
    volumes:
      - snipphub-data-prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  snipphub-data-prod: