version: "3.3"

services:
  snipphub-backend:
    image: snipphub-backend:prod
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - snipphub-data-prod:/data/db
    ports:
      - 27017:27017
volumes:
  snipphub-data-prod: